# Temporary Explorative Data Analyse

## Charger les données

In [7]:
import pandas as pd
import numpy as np
import glob

In [ ]:
df_linkedin = pd.read_excel('scraping_results/result_linkedin.com.xlsx')
df_linkedin.head()

,config_name,domain,country,currency,date,brand,start_url,start_url_formatted,url,entreprise,poste,description,date_de_publication,nb_candidats,location
0,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4386503400/...,RSM France,Consultant Senior Data & IA H/F (75),Rejoignez RSM et participez à une aventure hum...,Republication il y a 2 semaines,26 personnes ont cliqué sur Postuler,"Paris, Île-de-France, France"
1,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4390938905/...,Capgemini Invent Giulia Arca,Consultante expérimentée / Consultant expérime...,Consultante expérimentée / Consultant expérime...,Republication il y a 2 semaines,64 candidats,"Issy-les-Moulineaux, Île-de-France, France"
2,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4392431203/...,GEC _ Global Experts Consulting,Consultant ServiceNow Technico-Fonctionnel – I...,Dans le cadre du déploiement de cas d’usage d’...,il y a 3 semaines,14 candidats,"Paris, Île-de-France, France"
3,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4389275158/...,Talan,Consulting - Consultant Confirmé / Senior – St...,"Description de l'entreprise Fondé en France, T...",il y a 1 mois,4 personnes ont cliqué sur Postuler,"Paris, Île-de-France, France"
4,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4402502434/...,Sia,Consultant(e) Senior Data Science & IA,Sia est un groupe international de conseil en ...,il y a 1 semaine,19 candidats,"Paris, Île-de-France, France"

In [ ]:
fichiers_xlsx = glob.glob("scraping_results/*.xlsx")

liste_dataframes = []

for fichier in fichiers_xlsx:
  df_temp = pd.read_excel(fichier)

  liste_dataframes.append(df_temp)

df_global = pd.concat(liste_dataframes, ignore_index=True)

df_global.head()

,config_name,domain,country,currency,date,brand,start_url,start_url_formatted,url,entreprise,poste,description,date_de_publication,nb_candidats,location,source_fichier,profil_recherche,experience
0,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4386503400/...,RSM France,Consultant Senior Data & IA H/F (75),Rejoignez RSM et participez à une aventure hum...,Republication il y a 2 semaines,26 personnes ont cliqué sur Postuler,"Paris, Île-de-France, France",scraping_results/result_linkedin.com.xlsx,NaN,NaN
1,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4390938905/...,Capgemini Invent Giulia Arca,Consultante expérimentée / Consultant expérime...,Consultante expérimentée / Consultant expérime...,Republication il y a 2 semaines,64 candidats,"Issy-les-Moulineaux, Île-de-France, France",scraping_results/result_linkedin.com.xlsx,NaN,NaN
2,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4392431203/...,GEC _ Global Experts Consulting,Consultant ServiceNow Technico-Fonctionnel – I...,Dans le cadre du déploiement de cas d’usage d’...,il y a 3 semaines,14 candidats,"Paris, Île-de-France, France",scraping_results/result_linkedin.com.xlsx,NaN,NaN
3,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4389275158/...,Talan,Consulting - Consultant Confirmé / Senior – St...,"Description de l'entreprise Fondé en France, T...",il y a 1 mois,4 personnes ont cliqué sur Postuler,"Paris, Île-de-France, France",scraping_results/result_linkedin.com.xlsx,NaN,NaN
4,linkedin.com,linkedin.com,France,EUR,2026-04-27,consultantia,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/search/?currentJ...,https://www.linkedin.com/jobs/view/4402502434/...,Sia,Consultant(e) Senior Data Science & IA,Sia est un groupe international de conseil en ...,il y a 1 semaine,19 candidats,"Paris, Île-de-France, France",scraping_results/result_linkedin.com.xlsx,NaN,NaN

In [11]:
# Clean irrelevant columns
df = df_global.drop(columns=['config_name','currency'])

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2472 entries, 0 to 2471
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   domain               2472 non-null   str
 1   country              2472 non-null   str
 2   date                 2472 non-null   datetime64[us]
 3   brand                2472 non-null   str
 4   start_url            2472 non-null   str
 5   start_url_formatted  2472 non-null   str
 6   url                  2469 non-null   str
 7   entreprise           2175 non-null   str
 8   poste                2457 non-null   str
 9   description          2455 non-null   str
 10  date_de_publication  1317 non-null   str
 11  nb_candidats         792 non-null    str
 12  location             2343 non-null   str
 13  source_fichier       2472 non-null   str
 14  profil_recherche     275 non-null    str
 15  experience           454 non-null    str
dtypes: datetime64[us](1), str(15)
memory usage: 309.1 KB

In [ ]:
df.value_counts('domain')

country
France    2472
Name: count, dtype: int64

In [18]:
df.iloc[0]["description"]

"Rejoignez RSM et participez à une aventure humaine et entrepreneuriale ! Mission RSM est devenu 6ème réseau mondial en Audit, Expertise Comptable et Conseil grâce à l’engagement de nos équipes. Dans notre bureau de Paris, plus de 600 expert∙e∙s évoluent au quotidien dans un environnement bienveillant et en constante évolution, où autonomie et prise d’initiatives sont valorisées. « Lors de mon arrivée, ce qui m’a tout de suite plu c’est la relation humaine et la proximité avec les associés. Les équipes grandissent, pour autant la gestion reste à taille humaine. » Antoine « Chez RSM toutes les conditions sont réunies pour progresser et aller de l’avant, c’est vraiment une très bonne école de formation. » Richard Chez RSM, chaque jour est une opportunité de grandir. Nous avons à cœur de faire évoluer nos collaborateur∙trice∙s tout en accompagnant nos clients avec excellence. Ainsi, 95% des collaborateurs nous recommandent. Si vous êtes passionné∙e, ambitieux∙se et prêt∙e à rejoindre une équipe soudée, vous êtes au bon endroit ! Votre rôle : Consultant Senior Data & IA, au sein de notre équipe DATA & IA (H/F) Le pôle conseil est un centre d'excellence national en matière de DATA & AI. Nous accompagnons clientèle diversifiée, de PME et d'ETI, françaises ou internationales (Energie, Private Equity, Industries, Services..) afin de répondre à leurs enjeux de structuration de leur approche data : Diagnostic de la maturité data, audit, schéma directeur et recommandations ; Amélioration continue des processus métier et de la qualité des données associées ; Mise en place d'outils de pilotage de la performance ; Mise en oeuvre de data platforms (lakehouse, cubes, rapports, applications) ; Gouvernance de données, ownership, lineage, master data management ; Accompagnement à l'adoption des outils, conduite du changement. En rejoignant notre équipe de 15 expert∙e∙s passionné∙e∙s , vous aurez pour missions : Réaliser des audits, animer des ateliers et des phases de discovery Product management, planifier, animer et communiquer auprès des sponsors Mettre en œuvre des plateformes de données (ETL, modélisation et visualisation) Capacité à définir et garantir des standards de développement et choix d'architecture Accompagner le processus de veille technologique du pôle Coacher des collaborateurs juniors Profil Formation : Master ou Bac+5 d’une formation Ingénieur Data (école d'ingénieur, Master SICG/MIAGE etc.) Expérience : Vous justifiez de 3-4 ans d’expérience (hors alternance et stage) en cabinet de conseil, ESN ou en entreprise au sein d’équipes Data. Vous avez une vraie appétence pour la proposition de solutions techniques et fonctionnelles. Qualités personnelles : Vous êtes curieux, rigoureux, avec un esprit analytique développé et avez envie d’apprendre auprès d'une équipe dynamique proposant des solutions pragmatiques et innovantes à une clientèle variée. Vous souhaitez être force de proposition et moteur dans la conception de solutions. Vous êtes reconnu pour votre proactivité face aux enjeux de la recherche et du développement. Compétences indispensables : Vous détenez une expertise en pilotage de la performance et business intelligence. Vous maitrisez les technologies et langages suivants : Python, Spark, SQL, API, Microsoft Fabric, Power BI. Vous êtes capable d’évoluer dans un environnement anglophone et ainsi proposer des solutions à nos clients internationaux. Compétences différenciantes : Vous maitrisez le déploiement d'applications web (Streamlit, FastAPI...), vous avez une expérience avec des infrastructures Cloud avancées (AWS, GCP) ou IA/Machine Learning. Ce que nous vous offrons Un accompagnement sur-mesure :\u202fparcours d’onboarding, formation aux outils et méthodologie RSM, accompagnement pour se former et évoluer (certifications, formations éditeur…). Un environnement de travail dynamique : des bureaux situés dans le 9 ème arrondissement de Paris, un séminaire annuel, des soirées, afterworks, conférences, une charte de télétravail. Une rémunération fixe\u202f(comprenant un 13ème mois) Des avantages :\u202f12 jours de RTT, carte Ticket Restaurant® Edenred, mutuelle et prévoyance. Chez RSM, nous croyons fermement à la diversité et à l’inclusion. Nous nous engageons à accueillir et intégrer tous les talents tout au long de leur parcours au sein du Groupe. La Fondation RSM joue un rôle clé dans cette mission, en soutenant des projets d’insertion professionnelle pour les personnes vulnérables et en situation de handicap. Envie de faire partie de l’aventure RSM ? Postulez dès maintenant et\u202fvenez grandir avec nous ! Atouts Choisir RSM, c’est intégrer un cabinet qui valorise la bienveillance, la proximité, l’audace et l’engagement. Vous aurez l’opportunité de développer votre potentiel au sein d’équipes motivées et pluridisciplinaires, tout en bénéficiant d’un accompagnement formateur. Notre stratégie « Grandir Ensemble » place l’humain au cœur de tous nos projets.\u202f\u202f Avec ECHO, notre démarche RSE, nous créons de la valeur utile et durable pour nos collaborateurs et clients en abordant 10 enjeux répartis en 5 axes : gouvernance, économie, environnement, société et social. Nous mesurons les résultats en toute transparence et valorisons les actions entreprises. Mot du recruteur Notre stratégie « Grandir Ensemble » place l’humain au cœur de tous nos projets.\u202f\u202f Avec ECHO, notre démarche RSE, nous créons de la valeur utile et durable pour nos collaborateurs et clients en abordant 10 enjeux répartis en 5 axes : gouvernance, économie, environnement, société et social. Nous mesurons les résultats en toute transparence et valorisons les actions entreprises.\u202f\u202f De plus, nous nous engageons à réduire les inégalités en soutenant des projets d’insertion professionnelle pour les personnes vulnérables et en situation de handicap, via notre Fondation RSM. … plus"

In [33]:
# Get indexes where experience is not null
exp_indices = df[df["experience"].notna()].index

exp_indices = np.random.permutation(exp_indices)

print(f"Offers with experience field extracted : {len(exp_indices)}")

Offers with experience field extracted : 454

In [39]:
# Créer un fichier markdown pour lire et même labelliser facilement
with open("echantillon_offres.md", "w", encoding="utf-8") as f:
  for index in exp_indices[:200]:
    poste = df.loc[index, "poste"]
    desc = df.loc[index, "description"]
    exp = df.loc[index, "experience"]

    f.write(f"# Offre ID : {index}\n")
    f.write(f"**Poste :** {poste}\n\n")
    f.write(f"**Expérience brute :** {exp}\n\n")
    f.write(f"**Description :**\n{desc}\n\n")
    f.write(f"**seniority_level :**\n\n")
    f.write("-" * 80 + "\n\n")

print("Fichier Markdown exporté ! Tu peux l'ouvrir dans VS Code.")

Fichier Markdown exporté ! Tu peux l'ouvrir dans VS Code.